# fly.toml app configuration file for da-mines Paper Minecraft server
# See https://fly.io/docs/reference/configuration/

app = 'da-mines'
primary_region = 'lax'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[build]
  image = 'itzg/minecraft-server:latest'

[env]
  TYPE = 'PAPER'
  EULA = 'TRUE'
  MEMORY = '2G'
  ENABLE_AUTOSTOP = 'TRUE'
  AUTOSTOP_TIMEOUT_EST = '120'
  AUTOSTOP_TIMEOUT_INIT = '120'
  AUTOSTOP_PKILL_USE_SUDO = 'TRUE'

[[mounts]]
  source = 'mc_data'
  destination = '/data'

[[services]]
  protocol = 'tcp'
  internal_port = 25565

  [[services.ports]]
    port = 25565

  [services.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

[[vm]]
  memory = '4gb'
  cpu_kind = 'shared'
  cpus = 2
